/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import iznajmljivanjeapp.domain.Zaposleni;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.event.MenuListener;

/**
 *
 * @author Djurkovic
 */
public class GlavniMeniView extends javax.swing.JFrame {

    /**
     * Creates new form GlavniMeniView
     */
    
    
    
    public void addDodeliSmeneListener(ActionListener l) { 
        menuItemDodeliSmene.addActionListener(l);
    }
    
    public void addMenuItemObrisiSmeneListener(ActionListener l) {
        menuItemObrisiSmene.addActionListener(l);
    }
   
    public void setStatistikaVisible(boolean b){ 
        btnStatistika.setVisible(b);
    }
    
    public void addMenuItemIznajmljivanjePretraziActionListener(ActionListener l) {
        menuItemIznajmljivanjePretrazi.addActionListener(l);
    }
    
    
    
    public void addStatistikaListener(ActionListener l) {
        btnStatistika.addActionListener(l);
    }
    
    public GlavniMeniView() {
        initComponents();
        podesiProzor();
        dodajSliku("/resources/logo.png");
    }

    public void addMenuItemIznajmljivanjeKreirajListener(ActionListener l ) {
        menuItemIznajmljivanjeKreiraj.addActionListener(l);
    }
   
    
    public void addMenuItemZaposleniPromenaPodatakaListener(ActionListener l) {
        menuItemZaposleniPromeniPodatke.addActionListener(l);
    }
    
    public void setAdmin(boolean b) {
        lblAdmin.setVisible(b);
    }

    public void addMenuItemZaposleniPretraziListener(ActionListener l) {
        menuItemZaposleniPretrazi.addActionListener(l);
    }

    public void addMenuItemZaposleniKreirajListener(ActionListener l) {
        menuItemZaposleniKreiraj.addActionListener(l);
    }

    public void addMenuItemVoziloPretraziListener(ActionListener l) {
        menuItemVoziloPretrazi.addActionListener(l);
    }

    public void addMenuItemVoziloKreirajListener(ActionListener l) {
        menuItemVoziloKreiraj.addActionListener(l);
    }

    public void addMenuItemVozacPregledListener(ActionListener l) {
        menuItemVozacPretrazi.addActionListener(l);
    }

    public void setMenuItemZaposleniKreirajVisible(boolean visible) {
        menuItemZaposleniKreiraj.setVisible(visible);
    }

    public void setMenuItemZaposleniPretraziVisible(boolean visible) {
        menuItemZaposleniPretrazi.setVisible(visible);
    }

    public void setSmenaVisible(boolean vis) {
        menuSmena.setVisible(vis);
    }

    public void addMenuItemVozacKreirajListener(ActionListener l) {
        menuItemVozacKreiraj.addActionListener(l);
    }

    public void addLogoutListener(ActionListener l) {
        btnLogout.addActionListener(l);
    }

    public void addOProgramuListener(MenuListener l) {
        menuOProgramu.addMenuListener(l);
    }

    public void addPodesavanjaListener(MenuListener l) {
        menuPodesavanja.addMenuListener(l);
    }

    public void setUlogovanoIme(String ime) {
        lblImePrezime.setText(ime);
    }

    private void podesiProzor() {
        setIconImage(new ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
        setLocationRelativeTo(null);
    }

    private void dodajSliku(String ime) {
        //crtanje slike iznad svih ostalih komponenti sa vrlo niskom transparentnoscu
        Slika slika = new Slika(new ImageIcon(getClass().getResource(ime)).getImage(), 0.06f);
        getLayeredPane().add(slika, JLayeredPane.PALETTE_LAYER);
        slika.setBounds(0, 0, getWidth(), getHeight());
        slika.setOpaque(false);
        slika.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDobrodosli = new javax.swing.JLabel();
        lblUlogovanKao = new javax.swing.JLabel();
        lblSistem = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblImePrezime = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnStatistika = new javax.swing.JButton();
        menuGlavniMeni = new javax.swing.JMenuBar();
        menuIznajmljivanje = new javax.swing.JMenu();
        menuItemIznajmljivanjeKreiraj = new javax.swing.JMenuItem();
        menuItemIznajmljivanjePretrazi = new javax.swing.JMenuItem();
        menuVozac = new javax.swing.JMenu();
        menuItemVozacKreiraj = new javax.swing.JMenuItem();
        menuItemVozacPretrazi = new javax.swing.JMenuItem();
        menuVozilo = new javax.swing.JMenu();
        menuItemVoziloKreiraj = new javax.swing.JMenuItem();
        menuItemVoziloPretrazi = new javax.swing.JMenuItem();
        menuSmena = new javax.swing.JMenu();
        menuItemDodeliSmene = new javax.swing.JMenuItem();
        menuItemObrisiSmene = new javax.swing.JMenuItem();
        menuZaposleni = new javax.swing.JMenu();
        menuItemZaposleniPromeniPodatke = new javax.swing.JMenuItem();
        menuItemZaposleniKreiraj = new javax.swing.JMenuItem();
        menuItemZaposleniPretrazi = new javax.swing.JMenuItem();
        menuPodesavanja = new javax.swing.JMenu();
        menuOProgramu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meni");
        setResizable(false);

        lblDobrodosli.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDobrodosli.setText("Dobrodošli.");

        lblUlogovanKao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUlogovanKao.setText("Ulogovani ste kao: ");

        lblSistem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblSistem.setText("Sistem za iznajmljivanje vozila ");

        btnLogout.setText("Kraj rada");

        lblImePrezime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 51, 0));
        lblAdmin.setText("Admin");

        btnStatistika.setText("Statistika");

        menuIznajmljivanje.setText("Iznajmljivanje");

        menuItemIznajmljivanjeKreiraj.setText("Kreiraj");
        menuIznajmljivanje.add(menuItemIznajmljivanjeKreiraj);

        menuItemIznajmljivanjePretrazi.setText("Pretraži");
        menuIznajmljivanje.add(menuItemIznajmljivanjePretrazi);

        menuGlavniMeni.add(menuIznajmljivanje);

        menuVozac.setText("Vozač");

        menuItemVozacKreiraj.setText("Kreiraj");
        menuVozac.add(menuItemVozacKreiraj);

        menuItemVozacPretrazi.setText("Pretraži");
        menuItemVozacPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVozacPretraziActionPerformed(evt);
            }
        });
        menuVozac.add(menuItemVozacPretrazi);

        menuGlavniMeni.add(menuVozac);

        menuVozilo.setText("Vozilo");

        menuItemVoziloKreiraj.setText("Kreiraj");
        menuVozilo.add(menuItemVoziloKreiraj);

        menuItemVoziloPretrazi.setText("Pretraži");
        menuVozilo.add(menuItemVoziloPretrazi);

        menuGlavniMeni.add(menuVozilo);

        menuSmena.setText("Smena");

        menuItemDodeliSmene.setText("Dodeli/Izmeni smene");
        menuSmena.add(menuItemDodeliSmene);

        menuItemObrisiSmene.setText("Obriši smene");
        menuItemObrisiSmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemObrisiSmeneActionPerformed(evt);
            }
        });
        menuSmena.add(menuItemObrisiSmene);

        menuGlavniMeni.add(menuSmena);

        menuZaposleni.setText("Zaposleni");

        menuItemZaposleniPromeniPodatke.setText("Promeni podatke");
        menuZaposleni.add(menuItemZaposleniPromeniPodatke);

        menuItemZaposleniKreiraj.setText("Kreiraj ");
        menuZaposleni.add(menuItemZaposleniKreiraj);

        menuItemZaposleniPretrazi.setText("Pretraži");
        menuZaposleni.add(menuItemZaposleniPretrazi);

        menuGlavniMeni.add(menuZaposleni);

        menuPodesavanja.setText("Podešavanja");
        menuGlavniMeni.add(menuPodesavanja);

        menuOProgramu.setText("O programu");
        menuGlavniMeni.add(menuOProgramu);

        setJMenuBar(menuGlavniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lblSistem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnStatistika, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUlogovanKao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImePrezime))
                            .addComponent(lblDobrodosli))))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSistem)
                .addGap(37, 37, 37)
                .addComponent(lblDobrodosli)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovanKao)
                    .addComponent(lblImePrezime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatistika, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemVozacPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVozacPretraziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemVozacPretraziActionPerformed

    private void menuItemObrisiSmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemObrisiSmeneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemObrisiSmeneActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnStatistika;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblDobrodosli;
    private javax.swing.JLabel lblImePrezime;
    private javax.swing.JLabel lblSistem;
    private javax.swing.JLabel lblUlogovanKao;
    private javax.swing.JMenuBar menuGlavniMeni;
    private javax.swing.JMenuItem menuItemDodeliSmene;
    private javax.swing.JMenuItem menuItemIznajmljivanjeKreiraj;
    private javax.swing.JMenuItem menuItemIznajmljivanjePretrazi;
    private javax.swing.JMenuItem menuItemObrisiSmene;
    private javax.swing.JMenuItem menuItemVozacKreiraj;
    private javax.swing.JMenuItem menuItemVozacPretrazi;
    private javax.swing.JMenuItem menuItemVoziloKreiraj;
    private javax.swing.JMenuItem menuItemVoziloPretrazi;
    private javax.swing.JMenuItem menuItemZaposleniKreiraj;
    private javax.swing.JMenuItem menuItemZaposleniPretrazi;
    private javax.swing.JMenuItem menuItemZaposleniPromeniPodatke;
    private javax.swing.JMenu menuIznajmljivanje;
    private javax.swing.JMenu menuOProgramu;
    private javax.swing.JMenu menuPodesavanja;
    private javax.swing.JMenu menuSmena;
    private javax.swing.JMenu menuVozac;
    private javax.swing.JMenu menuVozilo;
    private javax.swing.JMenu menuZaposleni;
    // End of variables declaration//GEN-END:variables

    public void setMenuItemZaposleniPromeniPodatkeVisible(boolean b) {
        menuItemZaposleniPromeniPodatke.setVisible(b);
    }
}
