/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.richdialogs;

import framework.model.KriterijumDescriptor;
import framework.model.KriterijumWrapper;
import framework.model.network.NetworkRequest;
import framework.model.network.NetworkResponse;
import iznajmljivanjeapp.domain.Vozac;
import iznajmljivanjeapp.domain.Vozilo;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import network.RequestManager;
import util.Kriterijum;
import util.KriterijumGUI;
import util.NumberFilter;
import util.UI.DugmeUtils;

/**
 *
 * @author Djurkovic
 */
public class KriterijumVozilo extends javax.swing.JDialog {

    private Frame parent;
    private List<KriterijumGUI> krits = new ArrayList<>();

    /**
     * Creates new form KriterijumVozilo
     */
    public KriterijumVozilo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.parent = parent;
        Collections.addAll(krits,
                new KriterijumGUI(Kriterijum.STRING, cbKlasa, txtKlasa, Vozilo.class, "klasa", ckKlasa),
                new KriterijumGUI(Kriterijum.STRING, cbProizvodjac, txtProizvodjac, Vozilo.class, "proizvodjac", ckProizvodjac),
                new KriterijumGUI(Kriterijum.DECIMAL, cbKupovnaCena, txtKupovnaCena, Vozilo.class, "kupovnaCena", ckKupovnaCena),
                new KriterijumGUI(Kriterijum.INTEGER, cbGodiste, txtGodiste, Vozilo.class, "godiste", ckGodiste),
                new KriterijumGUI(Kriterijum.STRING, cbImeModela, txtImeModela, Vozilo.class, "imeModela", ckImeModela),
                new KriterijumGUI(Kriterijum.KATEGORIJAENUM, cbKategorija, txtKategorija, Vozilo.class, "kategorija", ckKategorija)
        );
        ((AbstractDocument) txtKupovnaCena.getDocument()).setDocumentFilter(new NumberFilter(NumberFilter.Mode.POSITIVE_DECIMAL));
        ((AbstractDocument) txtGodiste.getDocument()).setDocumentFilter(new NumberFilter(NumberFilter.Mode.INTEGER_ONLY));
        
        DugmeUtils.<Vozilo>registrujPretrazi(parent, this, btnPretrazi, krits, "vozila", "vozilo/vrati_sve", PregledVozilo.class,KriterijumWrapper.DepthLevel.SHALLOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbKlasa = new javax.swing.JComboBox<>();
        cbProizvodjac = new javax.swing.JComboBox<>();
        cbKupovnaCena = new javax.swing.JComboBox<>();
        cbGodiste = new javax.swing.JComboBox<>();
        cbKategorija = new javax.swing.JComboBox<>();
        cbImeModela = new javax.swing.JComboBox<>();
        txtKlasa = new javax.swing.JTextField();
        ckKlasa = new javax.swing.JCheckBox();
        txtProizvodjac = new javax.swing.JTextField();
        ckProizvodjac = new javax.swing.JCheckBox();
        txtKupovnaCena = new javax.swing.JTextField();
        ckKupovnaCena = new javax.swing.JCheckBox();
        txtGodiste = new javax.swing.JTextField();
        ckGodiste = new javax.swing.JCheckBox();
        txtImeModela = new javax.swing.JTextField();
        ckImeModela = new javax.swing.JCheckBox();
        txtKategorija = new javax.swing.JTextField();
        ckKategorija = new javax.swing.JCheckBox();
        btnPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Kriterijumi pretrage vozila");

        jLabel2.setText("Klasa:");

        jLabel3.setText("Proizvođač:");

        jLabel4.setText("Kupovna cena:");

        jLabel5.setText("Godište:");

        jLabel6.setText("Ime modela:");

        jLabel7.setText("Kategorija:");

        cbKlasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Sadrži", "Pripada" }));

        cbProizvodjac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Sadrži", "Pripada" }));

        cbKupovnaCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Veće od", "Manje od" }));

        cbGodiste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Veće od", "Manje od" }));

        cbKategorija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Pripada" }));

        cbImeModela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Sadrži", "Pripada" }));

        ckKlasa.setText("Negiraj?");

        ckProizvodjac.setText("Negiraj?");

        ckKupovnaCena.setText("Negiraj?");

        ckGodiste.setText("Negiraj?");

        ckImeModela.setText("Negiraj?");

        ckKategorija.setText("Negiraj?");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(61, 61, 61)
                                        .addComponent(cbKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckKlasa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckProizvodjac))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckKategorija))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckGodiste))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbKupovnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtKupovnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckKupovnaCena))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckImeModela)))))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ckKlasa)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckProizvodjac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbKupovnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKupovnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKupovnaCena))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckGodiste))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckImeModela))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKategorija))
                .addGap(34, 34, 34)
                .addComponent(btnPretrazi)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        
    }//GEN-LAST:event_btnPretraziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KriterijumVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KriterijumVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KriterijumVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KriterijumVozilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KriterijumVozilo dialog = new KriterijumVozilo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JComboBox<String> cbGodiste;
    private javax.swing.JComboBox<String> cbImeModela;
    private javax.swing.JComboBox<String> cbKategorija;
    private javax.swing.JComboBox<String> cbKlasa;
    private javax.swing.JComboBox<String> cbKupovnaCena;
    private javax.swing.JComboBox<String> cbProizvodjac;
    private javax.swing.JCheckBox ckGodiste;
    private javax.swing.JCheckBox ckImeModela;
    private javax.swing.JCheckBox ckKategorija;
    private javax.swing.JCheckBox ckKlasa;
    private javax.swing.JCheckBox ckKupovnaCena;
    private javax.swing.JCheckBox ckProizvodjac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtGodiste;
    private javax.swing.JTextField txtImeModela;
    private javax.swing.JTextField txtKategorija;
    private javax.swing.JTextField txtKlasa;
    private javax.swing.JTextField txtKupovnaCena;
    private javax.swing.JTextField txtProizvodjac;
    // End of variables declaration//GEN-END:variables
}
