/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.richdialogs;

import framework.model.FieldDescriptor;
import framework.model.KriterijumWrapper;
import iznajmljivanjeapp.domain.Dozvola;
import iznajmljivanjeapp.domain.Iznajmljivanje;
import iznajmljivanjeapp.domain.Smena;
import iznajmljivanjeapp.domain.TerminDezurstva;
import iznajmljivanjeapp.domain.Vozac;
import iznajmljivanjeapp.domain.Vozilo;
import iznajmljivanjeapp.domain.Zaposleni;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.text.AbstractDocument;
import util.Kriterijum;
import util.KriterijumGUI;
import util.NumberFilter;
import util.UI.DugmeUtils;

/**
 *
 * @author Djurkovic
 */
public class KriterijumIznajmljivanje extends javax.swing.JDialog {

    /**
     * Creates new form KriterijumIznajmljivanje
     */
    private List<KriterijumGUI> krits = new ArrayList<>();
    private java.awt.Frame parent;

    public KriterijumIznajmljivanje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.parent = parent;

        Collections.addAll(krits,
                new KriterijumGUI(Kriterijum.DATE, cbDatumDonjaGranica, dcDatumSklapanjaDonjaGranica, Iznajmljivanje.class, "datumSklapanja", null),
                new KriterijumGUI(Kriterijum.DATE, cbDatumGornjaGranica, dcDatumSklapanjaGornjaGranica, Iznajmljivanje.class, "datumSklapanja", null),
                new KriterijumGUI(Kriterijum.DECIMAL, cbUkupanIznos, txtUkupanIznos, Iznajmljivanje.class, "ukupanIznos", ckUkupanIznos),
                new KriterijumGUI(Kriterijum.STRING, cbVozac, txtVozac, Vozac.class, "email", ckEmailVozaca),
                new KriterijumGUI(Kriterijum.STRING, cbZaposleni, txtZaposleni, Zaposleni.class, "email", ckEmailZaposlenog),
                new KriterijumGUI(Kriterijum.STRING, cbImeModela, txtImeModela, Vozilo.class, "imeModela", null),
                new KriterijumGUI(Kriterijum.STRING, cbProizvodjac, txtProizvodjac, Vozilo.class, "proizvodjac", null)
        );
        List<FieldDescriptor> fs = new ArrayList<>();
        try {
            Collections.addAll(fs, 
                    new FieldDescriptor(Vozilo.class.getName(),"stavke"),
                    new FieldDescriptor(Zaposleni.class.getName(),"smene")
                    );
        }
        catch(Exception e) {
            SwingUtilities.invokeLater(() -> dispose());
            JOptionPane.showMessageDialog(null, "Greška pri prikazivanju kriterijuma za iznajmljivanje.","Greška",JOptionPane.ERROR_MESSAGE);
            return;
        }

        ((AbstractDocument) txtUkupanIznos.getDocument()).setDocumentFilter(new NumberFilter(NumberFilter.Mode.POSITIVE_DECIMAL));
        DugmeUtils.<Iznajmljivanje>registrujPretrazi(
                parent,
                this,
                btnPretrazi,
                krits,
                "iznajmljivanja",
                "iznajmljivanje/vrati_sve",
                PregledIznajmljivanje.class,
                () -> 
                        txtImeModela.getText().isEmpty() && txtProizvodjac.getText().isEmpty() ? 
                                new KriterijumWrapper(List.of(),KriterijumWrapper.DepthLevel.SHALLOW,List.of()) : 
                                new KriterijumWrapper(List.of(),KriterijumWrapper.DepthLevel.FULL,fs,List.of(Smena.class.getName(),TerminDezurstva.class.getName(),Dozvola.class.getName()))
                );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        lblKriterijum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dcDatumSklapanjaDonjaGranica = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtZaposleni = new javax.swing.JTextField();
        txtVozac = new javax.swing.JTextField();
        txtUkupanIznos = new javax.swing.JTextField();
        txtImeModela = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        cbZaposleni = new javax.swing.JComboBox<>();
        cbImeModela = new javax.swing.JComboBox<>();
        cbVozac = new javax.swing.JComboBox<>();
        cbUkupanIznos = new javax.swing.JComboBox<>();
        dcDatumSklapanjaGornjaGranica = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cbProizvodjac = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtProizvodjac = new javax.swing.JTextField();
        ckEmailVozaca = new javax.swing.JCheckBox();
        ckUkupanIznos = new javax.swing.JCheckBox();
        ckEmailZaposlenog = new javax.swing.JCheckBox();
        cbDatumDonjaGranica = new javax.swing.JComboBox<>();
        cbDatumGornjaGranica = new javax.swing.JComboBox<>();

        jCheckBox4.setText("Negiraj?");

        jCheckBox6.setText("Negiraj?");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga iznajmljivanja");
        setResizable(false);

        lblKriterijum.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblKriterijum.setText("Kriterijumi pretrage iznajmljivanja");

        jLabel1.setText("Datum sklapanja donja granica:");

        jLabel2.setText("Ukupan iznos:");

        jLabel3.setText("Email vozača:");

        jLabel4.setText("Email zaposlenog:");

        jLabel5.setText("Odnosi se na vozilo modela:");

        btnPretrazi.setText("Pretraži");

        cbZaposleni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Sadrži", "Pripada" }));

        cbImeModela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Sadrži", "Pripada" }));

        cbVozac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Sadrži", "Pripada" }));

        cbUkupanIznos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Različito od", "Veće od", "Manje od" }));

        jLabel6.setText("Datum sklapanja gornja granica:");

        cbProizvodjac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jednako", "Sadrži", "Pripada" }));

        jLabel7.setText("Odnosi se na vozilo proizvodjača:");

        ckEmailVozaca.setText("Negiraj?");

        ckUkupanIznos.setText("Negiraj?");

        ckEmailZaposlenog.setText("Negiraj?");

        cbDatumDonjaGranica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veće od" }));
        cbDatumDonjaGranica.setToolTipText("");

        cbDatumGornjaGranica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manje od" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(cbImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVozac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbDatumDonjaGranica, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dcDatumSklapanjaDonjaGranica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbDatumGornjaGranica, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dcDatumSklapanjaGornjaGranica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckEmailVozaca)
                    .addComponent(ckUkupanIznos)
                    .addComponent(ckEmailZaposlenog))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblKriterijum)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblKriterijum)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDatumDonjaGranica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(dcDatumSklapanjaDonjaGranica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDatumGornjaGranica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(dcDatumSklapanjaGornjaGranica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckUkupanIznos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckEmailVozaca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckEmailZaposlenog))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImeModela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KriterijumIznajmljivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KriterijumIznajmljivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KriterijumIznajmljivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KriterijumIznajmljivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KriterijumIznajmljivanje dialog = new KriterijumIznajmljivanje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JComboBox<String> cbDatumDonjaGranica;
    private javax.swing.JComboBox<String> cbDatumGornjaGranica;
    private javax.swing.JComboBox<String> cbImeModela;
    private javax.swing.JComboBox<String> cbProizvodjac;
    private javax.swing.JComboBox<String> cbUkupanIznos;
    private javax.swing.JComboBox<String> cbVozac;
    private javax.swing.JComboBox<String> cbZaposleni;
    private javax.swing.JCheckBox ckEmailVozaca;
    private javax.swing.JCheckBox ckEmailZaposlenog;
    private javax.swing.JCheckBox ckUkupanIznos;
    private com.toedter.calendar.JDateChooser dcDatumSklapanjaDonjaGranica;
    private com.toedter.calendar.JDateChooser dcDatumSklapanjaGornjaGranica;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblKriterijum;
    private javax.swing.JTextField txtImeModela;
    private javax.swing.JTextField txtProizvodjac;
    private javax.swing.JTextField txtUkupanIznos;
    private javax.swing.JTextField txtVozac;
    private javax.swing.JTextField txtZaposleni;
    // End of variables declaration//GEN-END:variables
}
