/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.richdialogs;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import framework.model.KriterijumWrapper;
import framework.model.network.NetworkRequest;
import framework.model.network.NetworkResponse;
import framework.orm.anotacije.vrednosnaogranicenja.Between;
import framework.simplelogger.LogLevel;
import framework.simplelogger.SimpleLogger;
import iznajmljivanjeapp.domain.Smena;
import iznajmljivanjeapp.domain.TerminDezurstva;
import iznajmljivanjeapp.domain.Zaposleni;
import iznajmljivanjeapp.domain.uslovniobjekti.SmenaUslov;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import model.tablemodel.EntityTableModel;
import model.tablemodel.EntityTableModelFactory;
import network.RequestManager;
import util.DateUtil;
import view.DodajZaposleni;

/**
 *
 * @author Djurkovic
 */
public class ObrisiSmene extends javax.swing.JDialog {

    /**
     * Creates new form DodajSmene
     */
    private java.awt.Frame parent;

    boolean dateValid = false;

    boolean redosledValid = false;
    boolean buducnostValid = false;

    private List<Zaposleni> sviZaposleni;
    private List<Zaposleni> izabraniZaposleni;
    private EntityTableModel<Zaposleni> m;

    public ObrisiSmene(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        ((JTextField) dcPrvaSmena.getDateEditor().getUiComponent()).setEditable(false);
        ((JTextField) dcPoslednjaSmena.getDateEditor().getUiComponent()).setEditable(false);

        this.parent = parent;
        Between b = Smena.class.getAnnotation(Between.class);
        int min, max;
        if (b == null) {
            min = 4;
            max = 8;
        } else {
            min = (int) b.donjaGranica();
            max = (int) b.gornjaGranica();
            if (!b.equal()) {
                min++;
                max--;
            }
        }

        btnIzbaci.setEnabled(false);

        izabraniZaposleni = new ArrayList<>();

        tblZaposleni.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                boolean hasSelection = tblZaposleni.getSelectedRowCount() > 0;
                btnIzbaci.setEnabled(hasSelection);
            }
        });

        try {
            tblZaposleni.setModel(EntityTableModelFactory.<Zaposleni>create(Zaposleni.class, izabraniZaposleni));
            this.m = (EntityTableModel<Zaposleni>) tblZaposleni.getModel();
            NetworkResponse resp = RequestManager.sendRequest(new NetworkRequest("zaposleni/vrati_sve", new KriterijumWrapper(List.of(), KriterijumWrapper.DepthLevel.NONE)));
            if (!resp.success) {
                SwingUtilities.invokeLater(() -> dispose());
                JOptionPane.showMessageDialog(null, "Došlo je do greške pri kreiranju forme za brisanje smena.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sviZaposleni = (List<Zaposleni>) resp.payload;

        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Došlo je do greške pri kreiranju forme za brisanje smena.", "Greška", JOptionPane.ERROR_MESSAGE);
            SwingUtilities.invokeLater(() -> dispose());
            return;

        }

        btnObrisiSmene.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dcPoslednjaSmena = new com.toedter.calendar.JDateChooser();
        dcPrvaSmena = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaposleni = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnObrisiSmene = new javax.swing.JButton();
        btnIzbaciSve = new javax.swing.JButton();
        btnIzbaci = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnDodajSve = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbSmene = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreacija Smena");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Obriši smene");

        jLabel2.setText("Datum prve smene:");

        jLabel3.setText("Datum poslednje smene:");

        tblZaposleni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZaposleni);

        jLabel5.setText("Zaposleni za brisanje smena");

        btnObrisiSmene.setText("Obrisi Smene");
        btnObrisiSmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiSmeneActionPerformed(evt);
            }
        });

        btnIzbaciSve.setText("Izbaci sve zaposlene");
        btnIzbaciSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciSveActionPerformed(evt);
            }
        });

        btnIzbaci.setText("Izbaci izabrane zaposlene");
        btnIzbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj zaposlene");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnDodajSve.setText("Dodaj sve zaposlene");
        btnDodajSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajSveActionPerformed(evt);
            }
        });

        jLabel4.setText("Tip smene:");

        cbSmene.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sve", "Vanredne", "Nevanredne" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnIzbaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIzbaciSve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDodajSve, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dcPrvaSmena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcPoslednjaSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSmene, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(196, 196, 196))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(btnObrisiSmene, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnObrisiSmene, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(dcPrvaSmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcPoslednjaSmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbSmene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIzbaci)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzbaciSve)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDodaj)
                                .addGap(18, 18, 18)
                                .addComponent(btnDodajSve)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        new DodajZaposleni(parent, true, sviZaposleni, (EntityTableModel<Zaposleni>) tblZaposleni.getModel()).setVisible(true);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnDodajSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajSveActionPerformed

        m.addEntiteti(sviZaposleni);
        sviZaposleni.clear();
    }//GEN-LAST:event_btnDodajSveActionPerformed

    private void btnIzbaciSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciSveActionPerformed

        var zs = m.getEntiteti();
        sviZaposleni.addAll(zs);
        zs.clear();
        m.fireTableDataChanged();
    }//GEN-LAST:event_btnIzbaciSveActionPerformed

    private void btnIzbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciActionPerformed
        int[] rs = tblZaposleni.getSelectedRows();
        Arrays.sort(rs);
        var zs = m.getEntiteti();
        for (int i = rs.length - 1; i >= 0; i--) {
            int r = rs[i];
            sviZaposleni.add(zs.get(r));
            zs.remove(r);
            m.fireTableRowsDeleted(r, r);
        }
    }//GEN-LAST:event_btnIzbaciActionPerformed

    private void btnObrisiSmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiSmeneActionPerformed

        var zs = m.getEntiteti();

        try {
            SmenaUslov smenaUslov = new SmenaUslov();
            if (dcPrvaSmena != null) {
                smenaUslov.datumOd = dcPrvaSmena.getDate();
            }
            if (dcPoslednjaSmena != null) {
                smenaUslov.datumDo = dcPoslednjaSmena.getDate();
            }
            smenaUslov.vanredne = switch((String)cbSmene.getSelectedItem()) {
                case "Sve" -> null;
                case "Vanredne" -> true;
                case "Nevanredne" -> false;
                default -> null;
            };
            smenaUslov.zaposleni = zs;
            
            NetworkResponse resp = RequestManager.sendRequest(new NetworkRequest("smena/obrisi_conditional", smenaUslov));
            if (!resp.success) {
                JOptionPane.showMessageDialog(null, "Došlo je do greške pri brisanju smena.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(null, "Uspešno brisanje smena.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Došlo je do greške pri brisanju smena.", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnObrisiSmeneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.installLookAndFeel("FlatLaf Light", "com.formdev.flatlaf.FlatLightLaf");
            UIManager.installLookAndFeel("FlatLaf Dark", "com.formdev.flatlaf.FlatDarkLaf");
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ObrisiSmene dialog = new ObrisiSmene(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajSve;
    private javax.swing.JButton btnIzbaci;
    private javax.swing.JButton btnIzbaciSve;
    private javax.swing.JButton btnObrisiSmene;
    private javax.swing.JComboBox<String> cbSmene;
    private com.toedter.calendar.JDateChooser dcPoslednjaSmena;
    private com.toedter.calendar.JDateChooser dcPrvaSmena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZaposleni;
    // End of variables declaration//GEN-END:variables

}
