/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.richdialogs;

import framework.model.KriterijumDescriptor;
import framework.model.KriterijumWrapper;
import iznajmljivanjeapp.domain.Iznajmljivanje;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import kontroler.IznajmljivanjeKontroler;
import model.tablemodel.EntityTableModelFactory;
import model.tablemodel.FieldAccessor;
import util.UI.DugmeUtils;
import view.IznajmljivanjeView;

/**
 *
 * @author Djurkovic
 */
public class PregledIznajmljivanje extends javax.swing.JDialog {

    /**
     * Creates new form PregledIznajmljivanje
     */
    private Frame parent;
    private List<KriterijumDescriptor> kds;

    public PregledIznajmljivanje(java.awt.Frame parent, boolean modal, List<Iznajmljivanje> iznajmljivanja, List<KriterijumDescriptor> kds) {
        super(parent, modal);
        initComponents();
        tblIznajmljivanja.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.parent = parent;
        this.kds = kds;
        setLocationRelativeTo(parent);

        try {
            tblIznajmljivanja.setModel(EntityTableModelFactory.<Iznajmljivanje>create(Iznajmljivanje.class, iznajmljivanja));
        } catch (Exception ex) {
            SwingUtilities.invokeLater(() -> dispose());
            JOptionPane.showMessageDialog(null, "Došlo je do greške pri generisanju tabele.", "Greška", JOptionPane.INFORMATION_MESSAGE);
        }
        boolean isFull = false;
        for(var k : kds) {
            if(k.imePolja().equals("imeModela") || k.imePolja().equals("proizvodjac")) {
                isFull = true;
                System.out.println("ok");
                break;
            }
        }
        List<FieldAccessor<Iznajmljivanje>> l = new ArrayList<FieldAccessor<Iznajmljivanje>>();
        l.add(Iznajmljivanje::getId);
        DugmeUtils.<Iznajmljivanje>registrujOsvezi(btnOsvezi, tblIznajmljivanja, kds, "iznajmljivanja", "iznajmljivanje/vrati_sve", isFull ? KriterijumWrapper.DepthLevel.FULL : KriterijumWrapper.DepthLevel.SHALLOW);
        
        
        DugmeUtils.<Iznajmljivanje>registrujPronadji(
                parent,
                Iznajmljivanje.class,
                btnPronadji,
                tblIznajmljivanja,
                "iznajmljivanje",
                "iznajmljivanje/vrati_sve",
                this,
                l,
                new String[]{"id"},
                IznajmljivanjeKontroler.class,
                IznajmljivanjeView.class,
                KriterijumWrapper.DepthLevel.FULL
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIznajmljivanja = new javax.swing.JTable();
        btnOsvezi = new javax.swing.JButton();
        btnPronadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled iznajmljivanja");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Pregled iznajmljivanja");

        tblIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIznajmljivanja);

        btnOsvezi.setText("Osveži");

        btnPronadji.setText("Pronađi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(253, 253, 253))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOsvezi;
    private javax.swing.JButton btnPronadji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIznajmljivanja;
    // End of variables declaration//GEN-END:variables
}
