/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.richdialogs;

import framework.model.KriterijumDescriptor;
import framework.model.KriterijumWrapper;
import iznajmljivanjeapp.domain.Vozilo;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import kontroler.VoziloKontroler;
import model.tablemodel.EntityTableModelFactory;
import model.tablemodel.FieldAccessor;
import util.UI.DugmeUtils;
import view.VoziloView;

/**
 *
 * @author Djurkovic
 */
public class PregledVozilo extends javax.swing.JDialog {

    /**
     * Creates new form PregledVozilo
     */
    private List<Vozilo> vozila;
    private List<KriterijumDescriptor> kds;
    private Frame parent;

    public PregledVozilo(java.awt.Frame parent, boolean modal, List<Vozilo> vozila, List<KriterijumDescriptor> kds) {
        super(parent, modal);
        initComponents();
        tblVozila.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.vozila = vozila;
        this.kds = kds;
        setLocationRelativeTo(parent);

        try {
            tblVozila.setModel(EntityTableModelFactory.<Vozilo>create(Vozilo.class, vozila));
        } catch (Exception ex) {
            dispose();
            JOptionPane.showMessageDialog(null, "Došlo je do greške pri generisanju tabele.", "Greška", JOptionPane.INFORMATION_MESSAGE);
        }

        DugmeUtils.<Vozilo>registrujOsvezi(btnOsvezi, tblVozila, kds, "vozila", "vozilo/vrati_sve",KriterijumWrapper.DepthLevel.SHALLOW);
        List<FieldAccessor<Vozilo>> l = new ArrayList<FieldAccessor<Vozilo>>();
        l.add(Vozilo::getId);
        
        
        DugmeUtils.<Vozilo>registrujPronadji(
                parent,
                Vozilo.class,
                btnPronadji,
                tblVozila,
                "vozilo",
                "vozilo/vrati_sve",
                this,
                l,
                new String[]{"id"},
                VoziloKontroler.class,
                VoziloView.class
        );
    }

    public static void main(String[] args) {
        new PregledVozilo(null, true, null, null).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVozila = new javax.swing.JTable();
        btnOsvezi = new javax.swing.JButton();
        btnPronadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled vozila");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Pregled vozila");

        tblVozila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVozila);

        btnOsvezi.setText("Osveži");

        btnPronadji.setText("Pronađi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOsvezi;
    private javax.swing.JButton btnPronadji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVozila;
    // End of variables declaration//GEN-END:variables
}
