/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.richdialogs;

import iznajmljivanjeapp.domain.StavkaIznajmljivanja;
import iznajmljivanjeapp.domain.Vozilo;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.TableModel;
import javax.swing.text.AbstractDocument;
import model.tablemodel.EntityTableModel;
import static util.DateUtil.daysBetween;
import static util.DateUtil.stripTime;
import util.DocumentListenerFactory;
import util.NumberFilter;

/**
 *
 * @author Djurkovic
 */
public class PromenaStavke extends javax.swing.JDialog {

    private boolean datumValid = true;

    private void proveriDatum() {
        Date poc = stripTime(dcDatumPocetka.getDate());
        Date zav = stripTime(dcDatumZavrsetka.getDate());

        if (poc != null && zav != null) {
            if (poc.equals(zav) || poc.after(zav)) {
                datumValid = false;
                lblStavkaError.setText("Datum početka mora biti pre datuma završetka.");
            } else if (daysBetween(poc, zav) < StavkaIznajmljivanja.MIN_DANA || daysBetween(poc, zav) > StavkaIznajmljivanja.MAX_DANA) {
                datumValid = false;
                lblStavkaError.setText("    Trajanje mora biti izmedju " + StavkaIznajmljivanja.MIN_DANA + " i " + StavkaIznajmljivanja.MAX_DANA + " dana.");
            } else {
                datumValid = true;
                lblStavkaError.setText("");
            }
        } else {
            datumValid = false;
            lblStavkaError.setText("");
        }
        proveri();
    }

    private StavkaIznajmljivanja stavka;
    private List<Vozilo> vozila;
    private EntityTableModel<StavkaIznajmljivanja> m;
    private JLabel ukupanIznos;

    /**
     * Creates new form PromenaStavke
     */
    public PromenaStavke(java.awt.Frame parent, boolean modal, StavkaIznajmljivanja stavka, List<Vozilo> vozila,EntityTableModel<StavkaIznajmljivanja> m, JLabel ukupanIznos) {
        super(parent, modal);
        initComponents();
        lblStavkaError.setText("");
        setLocationRelativeTo(parent);
        this.stavka = stavka;
        this.vozila = vozila;
        this.m = m;
        this.ukupanIznos = ukupanIznos;
        napuniGUI();
        dcDatumPocetka.getDateEditor().addPropertyChangeListener("date", e -> {
            proveriDatum();
        });
        dcDatumZavrsetka.getDateEditor().addPropertyChangeListener("date", e -> {
            proveriDatum();
        });
        ((AbstractDocument) txtIznos.getDocument()).setDocumentFilter(new NumberFilter(NumberFilter.Mode.POSITIVE_DECIMAL));
        txtIznos.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveri()));
        
        btnPromeni.addActionListener(e -> {
            dispose();
            double stariIznos = stavka.getIznos();
            stavka.setDatumPocetka(dcDatumPocetka.getDate());
            stavka.setDatumZavrsetka(dcDatumZavrsetka.getDate());
            stavka.setIznos(Double.parseDouble(txtIznos.getText()));
            stavka.setVozilo((Vozilo)cbVozilo.getSelectedItem());
            ukupanIznos.setText(Double.toString(Double.parseDouble(ukupanIznos.getText()) - stariIznos + stavka.getIznos()));
            m.fireTableDataChanged();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDatumPocetka = new javax.swing.JLabel();
        lblDatumZavrsetka = new javax.swing.JLabel();
        lblVozilo = new javax.swing.JLabel();
        lblIznos = new javax.swing.JLabel();
        dcDatumPocetka = new com.toedter.calendar.JDateChooser();
        cbVozilo = new javax.swing.JComboBox<>();
        txtIznos = new javax.swing.JTextField();
        lblStavkaError = new javax.swing.JLabel();
        dcDatumZavrsetka = new com.toedter.calendar.JDateChooser();
        btnPromeni = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Promena Stavke");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stavka Iznajmljivanja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblDatumPocetka.setText("Datum Početka:");

        lblDatumZavrsetka.setText("Datum Završetka:");

        lblVozilo.setText("Vozilo:");

        lblIznos.setText("Iznos:");

        lblStavkaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblStavkaError.setForeground(new java.awt.Color(255, 0, 0));
        lblStavkaError.setText("Datum početka mora biti pre datuma završetka.");

        btnPromeni.setText("Promeni");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDatumZavrsetka)
                                .addGap(9, 9, 9)
                                .addComponent(dcDatumZavrsetka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDatumPocetka)
                                .addGap(18, 18, 18)
                                .addComponent(dcDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVozilo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIznos)
                                .addGap(18, 18, 18)
                                .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblStavkaError))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnPromeni)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDatumPocetka)
                    .addComponent(dcDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblDatumZavrsetka))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(dcDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVozilo)
                    .addComponent(cbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIznos)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStavkaError)
                .addGap(18, 18, 18)
                .addComponent(btnPromeni)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Promena Stavke");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPromeni;
    private javax.swing.JComboBox<Vozilo> cbVozilo;
    private com.toedter.calendar.JDateChooser dcDatumPocetka;
    private com.toedter.calendar.JDateChooser dcDatumZavrsetka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDatumPocetka;
    private javax.swing.JLabel lblDatumZavrsetka;
    private javax.swing.JLabel lblIznos;
    private javax.swing.JLabel lblStavkaError;
    private javax.swing.JLabel lblVozilo;
    private javax.swing.JTextField txtIznos;
    // End of variables declaration//GEN-END:variables

    private void napuniGUI() {
        dcDatumPocetka.setDate(stavka.getDatumPocetka());
        dcDatumZavrsetka.setDate(stavka.getDatumZavrsetka());
        txtIznos.setText(stavka.getIznos().toString());

        for (var v : vozila) {
            cbVozilo.addItem(v);
        }
        cbVozilo.setSelectedItem(stavka.getVozilo());

    }

    private void proveri() {
        btnPromeni.setEnabled(datumValid && !txtIznos.getText().isEmpty());
    }
}
