/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.richdialogs;

import framework.model.KriterijumDescriptor;
import framework.model.network.NetworkRequest;
import framework.model.network.NetworkResponse;
import framework.simplelogger.LogLevel;
import framework.simplelogger.SimpleLogger;
import iznajmljivanjeapp.bezbednost.PasswordHasher;
import iznajmljivanjeapp.domain.Zaposleni;
import java.util.Base64;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import kontroler.LoginKontroler;
import model.LoginModel;
import network.RequestManager;
import util.DocumentListenerFactory;
import view.GlavniMeniView;
import view.LoginView;
import view.Slika;

/**
 *
 * @author Djurkovic
 */
public class PromenaPodataka extends javax.swing.JDialog {

    /**
     * Creates new form PromenaPodataka
     */
    private java.awt.Frame parent;

    private Zaposleni zaposleni;
    private Pattern p = Pattern.compile("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$"); //regex za mejl format
    private boolean mailValid = true;
    private boolean duzinaValid = true;

    public PromenaPodataka(java.awt.Frame parent, boolean modal, Zaposleni zaposleni) {
        super(parent, modal);
        this.parent = parent;
        this.zaposleni = zaposleni;
        initComponents();
        setLocationRelativeTo(parent);
        podesiProzor();
        dodajSliku("/resources/icon.png");
        if (zaposleni == null) {
            dispose();
            JOptionPane.showMessageDialog(null, "Došlo je do greške pri pokušaju promene podataka.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtIme.setText(zaposleni.getIme());
        txtPrezime.setText(zaposleni.getPrezime());
        txtEmail.setText(zaposleni.getEmail());

        lblMailError.setVisible(false);
        lblSifraError.setVisible(false);

        txtIme.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveriPolja()));
        txtPrezime.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveriPolja()));
        txtEmail.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveriPolja()));
        txtEmail.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveriMejl()));
        txtStaraSifra.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveriPolja()));
        txtNovaSifra.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveriPolja()));
        txtNovaSifra.getDocument().addDocumentListener(DocumentListenerFactory.create(d -> proveriDuzina()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNovaSifra = new javax.swing.JPasswordField();
        txtStaraSifra = new javax.swing.JPasswordField();
        cbPromeniSifru = new javax.swing.JCheckBox();
        btnPromeni = new javax.swing.JButton();
        lblMailError = new javax.swing.JLabel();
        lblSifraError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Promena podataka");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Promena Podataka");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabel5.setText("Stara šifra:");

        jLabel6.setText("Nova šifra:");

        txtNovaSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaSifraActionPerformed(evt);
            }
        });

        cbPromeniSifru.setSelected(true);
        cbPromeniSifru.setText("Promeni šifru?");
        cbPromeniSifru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPromeniSifruActionPerformed(evt);
            }
        });

        btnPromeni.setText("Promeni");
        btnPromeni.setEnabled(false);
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });

        lblMailError.setForeground(new java.awt.Color(255, 0, 0));
        lblMailError.setText("Mejl mora biti validnog formata.");

        lblSifraError.setForeground(new java.awt.Color(255, 0, 0));
        lblSifraError.setText("Šifra mora imati barem 8 karaktera.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblSifraError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lblMailError)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtPrezime)
                                    .addComponent(txtEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNovaSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStaraSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPromeni, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbPromeniSifru)
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMailError)
                .addGap(18, 18, 18)
                .addComponent(cbPromeniSifru)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaraSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovaSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblSifraError)
                .addGap(18, 18, 18)
                .addComponent(btnPromeni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void podesiProzor() {
        setIconImage(new ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
    }

    private void dodajSliku(String ime) {
        //crtanje slike iznad svih ostalih komponenti sa vrlo niskom transparentnoscu
        Slika slika = new Slika(new ImageIcon(getClass().getResource(ime)).getImage(), 0.06f);
        getLayeredPane().add(slika, JLayeredPane.PALETTE_LAYER);
        slika.setBounds(0, 0, getWidth(), getHeight());
        slika.setOpaque(false);
        slika.setFocusable(false);
    }


    private void txtNovaSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaSifraActionPerformed

    private void cbPromeniSifruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPromeniSifruActionPerformed
        txtStaraSifra.setEnabled(cbPromeniSifru.isSelected());
        txtNovaSifra.setEnabled(cbPromeniSifru.isSelected());
        proveriPolja();
        proveriDuzina();
    }//GEN-LAST:event_cbPromeniSifruActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        try {
            Zaposleni z = new Zaposleni();
            z.setId(zaposleni.getId());
            z.setIme(txtIme.getText());
            z.setPrezime(txtPrezime.getText());
            z.setEmail(txtEmail.getText());
            if(cbPromeniSifru.isSelected()) {
                z.setSifra(new String(txtNovaSifra.getPassword()));
            }
            NetworkResponse resp = RequestManager.sendRequest(new NetworkRequest("zaposleni/vrati_sve", List.of(new KriterijumDescriptor(Zaposleni.class, "id", "=", zaposleni.getId()))));
            if (!resp.success) {
                JOptionPane.showMessageDialog(null, "Došlo je do greške pri promeni podataka. Pokušajte ponovo.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            List<Zaposleni> l = (List<Zaposleni>) resp.payload;
            if (l.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Došlo je do greške pri identifikaciji. Molimo ulogujte se ponovo.", "Greška", JOptionPane.ERROR_MESSAGE);
                dispose();
                parent.dispose();
                LoginView v = new LoginView();
                LoginModel m = new LoginModel();
                LoginKontroler p = new LoginKontroler(v, m);
                v.setVisible(true);
                return;
            }
            Zaposleni vracen = l.getFirst();
            if( cbPromeniSifru.isSelected() && (!vracen.getSifra().equals(zaposleni.getSifra()) 
                    || !vracen.getSalt().equals(zaposleni.getSalt()) 
                    || !vracen.getSifra().equals(PasswordHasher.hash(new String(txtStaraSifra.getPassword()), Base64.getDecoder().decode(zaposleni.getSalt()))))) {
                JOptionPane.showMessageDialog(null, "Uneta stara šifra nije ispravna. Pokušajte ponovo.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            NetworkResponse resp2 = RequestManager.sendRequest(new NetworkRequest("zaposleni/promeni", z));
            if (!resp2.success) {
                JOptionPane.showMessageDialog(null, resp2.responseMessage, "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            dispose();
            zaposleni.setIme(z.getIme());
            zaposleni.setPrezime(z.getPrezime());
            zaposleni.setEmail(z.getEmail());
            ((GlavniMeniView)parent).setUlogovanoIme(zaposleni.getIme() + " " + zaposleni.getPrezime());
            JOptionPane.showMessageDialog(null, "Uspešno promenjeni podaci.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(ClassCastException ex) {
            SimpleLogger.log(LogLevel.LOG_ERROR, "Pozvan iz neocekivanog roditelja");
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Došlo je do greške pri promeni podataka. Molimo pokušajte kasnije.", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPromeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromenaPodataka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromenaPodataka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromenaPodataka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromenaPodataka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PromenaPodataka dialog = new PromenaPodataka(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPromeni;
    private javax.swing.JCheckBox cbPromeniSifru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMailError;
    private javax.swing.JLabel lblSifraError;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JPasswordField txtNovaSifra;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JPasswordField txtStaraSifra;
    // End of variables declaration//GEN-END:variables

    private void proveriPolja() {
        if (txtIme.getText().isEmpty()
                || txtPrezime.getText().isEmpty()
                || txtEmail.getText().isEmpty()
                || (cbPromeniSifru.isSelected() && ((new String(txtStaraSifra.getPassword()).isEmpty()) || (new String(txtNovaSifra.getPassword()).isEmpty())))) {
            btnPromeni.setEnabled(false);
        } else {
            btnPromeni.setEnabled(mailValid && (!cbPromeniSifru.isSelected() || duzinaValid));
        }
    }

    private void proveriMejl() {
        Matcher m = p.matcher(txtEmail.getText());
        mailValid = m.matches();
        if (mailValid || txtEmail.getText().isEmpty()) {
            lblMailError.setVisible(false);
        } else {
            lblMailError.setVisible(true);
        }
    }

    private void proveriDuzina() {
        duzinaValid = !cbPromeniSifru.isSelected() || txtNovaSifra.getPassword().length == 0 || txtNovaSifra.getPassword().length >= 8;
        lblSifraError.setVisible(!duzinaValid);
    }

}
